# Generated by Django 3.2.8 on 2021-10-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('city', models.CharField(max_length=400)),
                ('address', models.TextField(default='')),
                ('maritialstatus', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Engaged', 'Engaged')], max_length=50)),
                ('contactno', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('biodata', models.FileField(blank=True, upload_to='files/')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
